base/urls.py
from django.urls import path
from . import views

app_name = 'base'
urlpatterns = [

    # General stuff
    path('', views.home, name='home'),
    path('questions', views.all_questions, name='all_questions'),
    path('questions/submit', views.add_question, name='ask_question'),
    path('questions/<int:id>', views.view_question, name='view_question'),
    path('questions/tagged/<str:tag>', views.tagged_questions, name='tagged'),
    path('questions/<int:question_id>/answer/submit',
         views.new_answer, name='new_answer'),
    path('inbox', views.inbox, name='inbox'),

    # Auth stuff
    path('auth/register', views.register, name='register'),
    path('auth/login', views.login, name='login'),
    path('users/<int:id>', views.profile, name='profile'),
    path('auth/logout', views.logout, name='logout'),
]

questacks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('ckeditor', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/questacks/all_questions.html
{% extends 'base.html' %}
{% load humanize %}

{% block content %}
<div class="px-2 d-flex justify-content-between align-items-center">
      <h1>All Questions</h1>
      <a href="{% url 'base:ask_question' %}" class="btn btn-primary">Ask Question</a>
</div>

<div class="btn-group">
      <a id="orderBtn" href="?order_by=newest" class="btn btn-outline-primary">Newest</a>
      <a id="orderBtn" href="?order_by=oldest" class="btn btn-outline-primary">Oldest</a>
      <a id="orderBtn" href="?order_by=popular" class="btn btn-outline-primary">Popular</a>
</div>

{% if questions %}
{% for question in questions %}

<!-- Questions -->
{% include 'partials/questions_detailed.html' %}

{% endfor %}
{% else %}

{% endif %}

<script>

      const orderBtns = document.querySelectorAll('#orderBtn')
      orderBtns.forEach(btn => {
            const urlParams = new URLSearchParams(window.location.search);
            const orderBy = urlParams.get('order_by');

            if (btn.innerHTML.toLowerCase() == orderBy) {
                  btn.className = 'btn btn-primary'
            }
      })
</script>
{% endblock content %}

templates/questacks/ask_question.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div style="width: 400px">
  <h1 class="display-4 my-3">Ask a Question</h1>
  <form action="" method="post">
      {% csrf_token %}
      {{ form|crispy }}

      <button type="submit" class="btn btn-primary my-3">Post</button>
      <a href="{% url 'base:home' %}" class="btn btn-secondary">Cancel</a>
  </form>
</div>

{% endblock content %}

templates/questacks/inbox.html
{% extends 'base.html' %}
{% load humanize %}

{% block content %}
{% if not inbox_items %}
<h1 class="display-4">No Inbox Items</h1>
{% else %}
{% for item in inbox_items %}
<div class="card p-2" style="width: 400px;">
      <div style="position: relative;" class="card-body px-0">
            <div class="mb-3">
                  <small class="text-muted" style="position: absolute; top: 0; left: 0;">{{ item.inbox_type }}</small>
                  <small class="text-muted" style="position: absolute; top: 0; right: 0;">
                        {{ item.created_at|naturaltime}}
                  </small>
            </div>
            <p class="card-title">
                  <a href="{% url 'base:view_question' item.target_question.id %}">{{ item.target_question.title }}</a>
            </p>
            <small class="card-subtitle">
                  {{ item.message|striptags }}
            </small>
      </div>
</div>
{% endfor %}
{% endif %}
{% endblock content %}

templates/questacks/tagged.html
{% extends 'base.html' %}
{% load humanize %}

{% block content %}
      {% if questions %}
        {% for question in questions %}
          
            <!-- Questions -->
            {% include 'partials/questions.html' %}
            
        {% endfor %}
      {% else %}

      {% endif %}
{% endblock content %}

templates/questacks/view_question.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load humanize %}
{% block content %}
<div style="position: relative; width: 1000px">
  <h1>{{ question.title }}</h1>
  <div class="stats d-flex justify-content-around align-items-start" style="width: 390px">
    <small>
      <div class="d-inline mr-2 text-muted">Asked</div>
      {{ question.created_at|naturaltime }}
    </small>
    <small>
      <div class="d-inline mr-2 text-muted">Active</div>
      {{ question.user.last_login|naturaltime }}
    </small>
    <small>
      <div class="d-inline mr-2 text-muted">Viewed</div>
      {{ question.views }} time{{ question.views|pluralize }}
    </small>
  </div>
  <hr />
  <div class="mt-4">{{ question_body|safe }}</div>

  <div class="d-flex justify-content-between mt-3">
    <div style="width: max-content">
      {% for tag in question.tag.all %}
      <div style="background: #d0e3f1; font-size: 12px" class="rounded d-inline mx-2 p-2">
        <a style="text-decoration: none !important" href="{% url 'base:tagged' tag %}">{{ tag }}</a>
      </div>
      {% endfor %}
    </div>
    <div class="rounded p-2 mb-3" style="background-color: #d9eaf7">
      <p style="font-size: 12px" class="text-muted m-0 p-0">
        Asked {{ question.created_at|date:'M, n' }} 'at {{ question.created_at|date:'H:i' }}
      </p>
      <img class="d-inline-block img-fluid p-0" src="{{ question.user.profile.profile_img.url }}"
        alt="{{ question.user.username }}" style="width: 35px; height: 35px; border-radius: 4px; object-fit: cover" />
      <div class="d-inline-block">
        <a href="{% url 'base:profile' question.user.id %}">{{ question.user.username }}</a><br />
        <div style="font-size: 12px" class="active">
          <label class="text-muted">Active</label>
          <label>{{ question.user.last_login|naturaltime }}</label>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="mt-5 d-block">
  {% if question.answer_set.count > 0 %}
  <h3 class="mb-3">
    {{ question.answer_set.count }}
    Answer{{question.answer_set.count|pluralize}}
  </h3>
  <div>
    {% for answer in question.answer_set.all %}
    <div class="card mb-2" style="width: 600px;">
      <div class="card-body">
        <div class="card-text">{{ answer.answer_text|safe }}</div>
        <div class="rounded p-2 mb-3" style="background-color: #d9eaf7; width: fit-content; float: right;">
          <p style="font-size: 12px" class="text-muted m-0 p-0">
            Answered {{ answer.created_at|date:'M, n' }} 'at {{ question.created_at|date:'H:i' }}
          </p>
          <img class="d-inline-block img-fluid p-0" src="{{ answer.user.profile.profile_img.url }}"
            alt="{{ answer.user.username }}" style="width: 35px; height: 35px; border-radius: 4px; object-fit: cover" />
          <div class="d-inline-block">
            <a href="{% url 'base:profile' question.user.id %}">{{ answer.user.username }}</a><br />
            <div style="font-size: 12px" class="active">
              <label class="text-muted">Active</label>
              <label>{{ answer.user.last_login|naturaltime }}</label>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% endif %}

  <h4 class="mt-5 mb-3">Your Answer</h4>
  <form action="{% url 'base:new_answer' question.id %}" method="POST">
    {% csrf_token %} {% crispy form %}
    <button id="submit" type="submit" class="btn btn-primary d-block my-3">
      Post Your Answer
    </button>
  </form>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" referrerpolicy="no-referrer"></script>
<!-- <script>
  if ($('textarea[name=answer_text]').val().trim() == '') {
    $('#submit').attr('disabled', true)
  }

  $('textarea[name=answer_text]').on('input', () => {
    $('#submit').attr('disabled', true)
    val = $(this).val().trim()
    if (val.length > 0) {
      $('#submit').attr('disabled', false)
    }
  })
</script> -->
{% endblock content %}