base/urls.py
from django.urls import path
from . import views

app_name = 'base'
urlpatterns = [

    # General stuff
    path('', views.home, name='home'),
    path('questions', views.all_questions, name='all_questions'),
    path('questions/submit', views.add_question, name='ask_question'),
    path('questions/<int:id>', views.view_question, name='view_question'),
    path('questions/tagged/<str:tag>', views.tagged_questions, name='tagged'),
    path('questions/<int:question_id>/answer/submit',
         views.new_answer, name='new_answer'),
    path('inbox', views.inbox, name='inbox'),

    # Auth stuff
    path('auth/register', views.register, name='register'),
    path('auth/login', views.login, name='login'),
    path('users/<int:id>', views.profile, name='profile'),
    path('auth/logout', views.logout, name='logout'),
]

questacks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('ckeditor', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'base:home' %}">QUES<span class="text-primary">tacks</span></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'base:all_questions' %}">Questions</a>
        </li>
      </ul>
      {% if not user.is_authenticated %}
      <ul class="ms-auto navbar-nav mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active btn btn-primary text-white mx-2" href="{% url 'base:login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active btn btn-secondary text-white mx-2" href="{% url 'base:register' %}">Signup</a>
        </li>
      </ul>
      {% else %}
      <ul class="ms-auto navbar-nav mb-2 mb-lg-0">
        <li class="nav-item">
          <!-- Drpdown -->
          <div class="dropdown">
            <button class="btn" type="button" id="dropdown" data-bs-toggle="dropdown" aria-expanded="false">
              <img src="{{ user.profile.profile_img.url }}" style="width: 33px; height: 33px; object-fit: cover"
                class="rounded-circle" alt="" />
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdown">
              <li>
                <a class="dropdown-item" href="{% url 'base:profile' user.id %}"><i class="fas fa-user"></i> Profile</a>
              </li>
              <li>
                <a class="dropdown-item" href="{% url 'base:logout' %}"><i class="fas fa-sign-out-alt"></i> Logout</a>
              </li>
            </ul>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link active mx-2" href="{% url 'base:inbox' %}">
            <i class="fas fa-inbox"></i>
          </a>
        </li>
      </ul>

      {% endif %}
    </div>
  </div>
</nav>

templates/partials/question_stats.html
{% load humanize %}

<div class="mr-3" style="font-size: 14px !important">
  <div
    style="border-color: #5eba7d !important; display: inline-block"
    class="text-center card mx-2"
  >
    <div
      class="card-body p-0"
      style="
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        width: 54px;
        height: 54px;
      "
    >
      <small class="card-title d-block">{{ question.answer_set.count }}</small>
      <small class="card-subtitle text-muted"
        >answer{{ question.answer_set.count|pluralize }}</small
      >
    </div>
  </div>

  <div
    style="border-color: #5eba7d !important; display: inline-block"
    class="text-center card mx-2"
  >
    <div
      class="card-body p-0"
      style="
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        width: 50px;
        height: 50px;
      "
    >
      <small class="card-title">{{ question.views }}</small>
      <small class="card-subtitle text-muted"
        >view{{ question.views|pluralize }}</small
      >
    </div>
  </div>
</div>

templates/partials/questions.html
{% load humanize %}

<div style="position: relative" class="p-3 d-flex border-bottom my-3">
  {% include 'partials/question_stats.html' %}
  <div>
    <h5 class="ms-1 mb-3" style="font-weight: normal;"><a style="text-decoration: none !important;"
        href="{% url 'base:view_question' question.id %}">{{ question.title }}</a></h3>
      <div style="width: max-content">
        {% for tag in question.tag.all %}
        <div style="background: #d0e3f1; font-size: 12px" class="rounded d-inline mx-2 p-2">
          <a style="text-decoration: none !important" href="{% url 'base:tagged' tag %}">{{ tag }}</a>
        </div>
        {% endfor %}
      </div>
      <small class="text-muted" style="position: absolute; bottom: 10px; right: 10px">
        Asked {{ question.created_at|naturaltime }}
        <a href="{% url 'base:profile' question.user.id %}">{{ question.user.username }}</a>
      </small>
  </div>
</div>

templates/partials/questions_detailed.html
{% load humanize %}

<div style="position: relative" class="p-3 d-flex border-bottom my-3">
  {% include 'partials/question_stats.html' %}
  <div>
    <h5 class="ms-1 mb-3" style="font-weight: normal">
      <a
        style="text-decoration: none !important"
        href="{% url 'base:view_question' question.id %}"
        >{{ question.title }}</a
      >
    </h5>
    <p>{{ question.question|striptags|truncatechars:100 }}</p>
    <div style="width: max-content">
      {% for tag in question.tag.all %}
      <div
        style="background: #d0e3f1; font-size: 12px"
        class="rounded d-inline mx-2 p-2"
      >
        <a
          style="text-decoration: none !important"
          href="{% url 'base:tagged' tag %}"
          >{{ tag }}</a
        >
      </div>
      {% endfor %}
    </div>
    <small
      class="text-muted"
      style="position: absolute; bottom: 10px; right: 10px"
    >
      Asked {{ question.created_at|naturaltime }}
      <a href="{% url 'base:profile' question.user.id %}">
        {{ question.user.username }}<br />
        <img
          src="{{ question.user.profile.profile_img.url }}"
          class="img-fluid"
          style="border-radius: 5px; width: 30px; height: 30px"
          alt=""
        />
      </a>
    </small>
  </div>
</div>